// @ts-nocheck
// Auto-generated by boneyard-js
// Import this file in your root layout or entry point to register bones.

if (typeof window !== 'undefined') {
  window.__BONEYARD_REGISTRY__ = window.__BONEYARD_REGISTRY__ || {};
}
